version: '3'

services:
  app:
    build: .
    volumes:
      - ./log_house:/home/local/
    ports:
      - "8888:8888"
    tty: true
    command: >
      sh -c '
        flutter pub get &&
        flutter run -d web-server --web-port=8888 --web-hostname=0.0.0.0
      '
